### ISSUE TITLE
Permission denied for any command in VM

### ISSUE THREAD

**Issue by proofoftom** [uberhacker/pantheon-local-drupal-development#4]
Vagrant 1.7.4
VirtualBox 5.0.2

```
vagrant@debian:~$ git-config
-bash: /vagrant/git-config.sh: Permission denied
```

**Comment by uberhacker** [comment]
See the Troubleshooting section in README.md.  Very likely you missed step 1 of the installation.

$ git config --global core.autocrlf false

**Comment by proofoftom** [comment]
Destroyed machine, pulled latest repo and re-tried with virtualbox 4.3.30, making sure I ran step 1 previous to cloning the repo and running vagrant up. See below:

The end of vagrant up...

```
==> default: Checking for corrupt, not cleanly closed and upgrade needing tables..
~/v/pantheon-local-drupal-development (master) $ vagrant ssh
Linux debian-7 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
You have mail.
vagrant@debian:~$ ls -la
total 108
drwxr-xr-x 4 vagrant vagrant  4096 Sep  4 06:33 .
drwxr-xr-x 3 root    root     4096 Aug 26 00:38 ..
-rw-r--r-- 1 vagrant vagrant     0 Sep  4 06:33 =2
-rw-r--r-- 1 vagrant vagrant  1319 Sep  4 06:33 .bash_aliases
-rw-r--r-- 1 vagrant vagrant   220 Aug 26 00:38 .bash_logout
-rw-r--r-- 1 vagrant vagrant  4071 Sep  4 06:33 .bashrc
drwxr-xr-x 4 vagrant vagrant  4096 Sep  4 06:33 .composer
-rw-r--r-- 1 vagrant vagrant 56618 Sep  4 06:32 .git-completion.bash
-rw-r--r-- 1 vagrant vagrant 16108 Sep  4 06:32 .git-prompt.sh
-rw-r--r-- 1 vagrant vagrant   675 Aug 26 00:38 .profile
drwx------ 2 vagrant vagrant  4096 Sep  4 06:30 .ssh
-rw-r--r-- 1 vagrant vagrant     5 Aug 26 00:38 .vbox_version
vagrant@debian:~$ git-config
-bash: /vagrant/git-config.sh: Permission denied
vagrant@debian:~$ dos2unix /vagrant/git-config.sh
dos2unix: converting file /vagrant/git-config.sh to Unix format ...
vagrant@debian:~$ git-config
-bash: /vagrant/git-config.sh: Permission denied
```

The =2 file is especially interesting...

**Comment by uberhacker** [comment]
What are the permissions of ~/v/pantheon-local-drupal-development?  See if
that directory has execute permission.

Try this from your Mac terminal session (not from inside the VM) after a
vagrant halt:

$ cd ~/v
$ sudo chmod -R +x pantheon-local-drupal-development/

Then vagrant up again and let me know if that makes a difference.

On Fri, Sep 4, 2015 at 1:41 AM, Tommy Cox notifications@github.com wrote:

> Destroyed machine and retried with virtualbox 4.3.30, ensuring I ran step
> 1 previous to cloning the repo and running vagrant up. See below:
> 
> The end of vagrant up...
> 
> ==> default: Checking for corrupt, not cleanly closed and upgrade needing tables..
> ~/v/pantheon-local-drupal-development (master) $ vagrant ssh
> Linux debian-7 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u3 x86_64
> 
> The programs included with the Debian GNU/Linux system are free software;
> the exact distribution terms for each program are described in the
> individual files in /usr/share/doc/*/copyright.
> 
> Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
> permitted by applicable law.
> You have mail.
> vagrant@debian:~$ ls -la
> total 108
> drwxr-xr-x 4 vagrant vagrant  4096 Sep  4 06:33 .
> drwxr-xr-x 3 root    root     4096 Aug 26 00:38 ..
> -rw-r--r-- 1 vagrant vagrant     0 Sep  4 06:33 =2
> -rw-r--r-- 1 vagrant vagrant  1319 Sep  4 06:33 .bash_aliases
> -rw-r--r-- 1 vagrant vagrant   220 Aug 26 00:38 .bash_logout
> -rw-r--r-- 1 vagrant vagrant  4071 Sep  4 06:33 .bashrc
> drwxr-xr-x 4 vagrant vagrant  4096 Sep  4 06:33 .composer
> -rw-r--r-- 1 vagrant vagrant 56618 Sep  4 06:32 .git-completion.bash
> -rw-r--r-- 1 vagrant vagrant 16108 Sep  4 06:32 .git-prompt.sh
> -rw-r--r-- 1 vagrant vagrant   675 Aug 26 00:38 .profile
> drwx------ 2 vagrant vagrant  4096 Sep  4 06:30 .ssh
> -rw-r--r-- 1 vagrant vagrant     5 Aug 26 00:38 .vbox_version
> vagrant@debian:~$ git-config
> -bash: /vagrant/git-config.sh: Permission denied
> vagrant@debian:~$ dos2unix /vagrant/git-config.sh
> dos2unix: converting file /vagrant/git-config.sh to Unix format ...
> vagrant@debian:~$ git-config
> -bash: /vagrant/git-config.sh: Permission denied
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/uberhacker/pantheon-local-drupal-development/issues/4#issuecomment-137659792
> .

## 

"God gave us two ears and one mouth to remind us we should listen twice as
much as we talk."

**Comment by proofoftom** [comment]
After pulling latest changes and using VirtualBox 4.3.30 the commands are now working in a fresh machine as expected.
